### ISSUE TITLE
installing lh-cpp with Vundle

### ISSUE THREAD

**Issue by failSafePlan** [LucHermitte/lh-cpp#2]
Being prompted to set mod!
What are the initial common settings to include in .vimrc file to get lh-cpp running?

**Comment by LucHermitte** [comment]
Hi. I'm not using Vundle but VAM that handles dependencies, so I'll try to guess.

It seems the interface has changed. Have you tried 
```vim
Plugin 'LucHermitte/lh-vim-lib'
Plugin 'LucHermitte/lh-tags'
Plugin 'LucHermitte/lh-dev'
Plugin 'LucHermitte/lh-brackets'
Plugin 'LucHermitte/searchInRuntime'
Plugin 'LucHermitte/mu-template'
Plugin 'tomtom/stakeholders_vim'
Plugin 'LucHermitte/lh-cpp'
```
?

Regarding calls to 
```vim
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
....
call vundle#end()
```
I expect it's already in place in your .vimrc. Otherwise, I'd recommend you use either VAM or vim-flavor as they understand the dependencies I declare for my plugins.

Otherwise, I don't set anything special in my vimrc that you'll find over there: https://github.com/LucHermitte/lh-misc/blob/master/vimrc_core.vim

Let me know if I answer your question.

**Comment by LucHermitte** [comment]
After seeing your question on SO, I see I did not understood it. 

What's your exact error message, and what are you doing ? (just starting vim? opening a C++ file? ...)

**Comment by failSafePlan** [comment]
Thank you so much for replying, here is a screen-shot of the error messages I get after enabling the plugin in my vimrc file. This happens when I use vim to edit files.  
![screenshot-3](https://cloud.githubusercontent.com/assets/7386358/13095295/d1c7050a-d536-11e5-84e0-f5109d0764d0.png)

**Comment by failSafePlan** [comment]
After installing all the plugins the error messages have been removed. Thank you.

**Comment by LucHermitte** [comment]
OK. Thanks.
