### ISSUE TITLE
Strange behavior if you already have the a.vim plugin

### ISSUE THREAD

**Issue by mellery451** [LucHermitte/lh-cpp#6]
I was an existing user of nacitar/a.vim and I did not realize that it is basically being provided by lh-cpp as well. When I have both plugins enabled, the `:A`  command seems to always want to create a new file (even when a valid alternate exists). I'm not sure what the specific problem is, but it seems that just disabling the nacitar/a.vim plugin makes things work again.

I'm not sure what the best long-term fix for this issue is, but I thought I would report the issue for you consideration.

**Comment by LucHermitte** [comment]
I wasn't aware of this other fork. Thank you for the information.
On my side, I've been shipping a fork of alternate for quite a long time now in order to give access to some internals functions in order to implement `:GOTOIMPL` command.

Lately, I've decided to start almost from scratch with a simplified and more easily tunable architecture: https://github.com/LucHermitte/alternate-lite

If you mix nacitar's fork and mine there may be problems indeed. However, I should eventually no longer rely internally on alternate. 

Note however than I plan eventually to support alternate `:A*` commands. In consequence, It'll be redundant with nacitar's fork.

I'll keep your issue around to track my (expected to be slow) progresses on the subject.

**Comment by LucHermitte** [comment]
I've updated alternate-lite in order to remove a.vim dependency.
If you keep nacitar/a.vim and alternate-lite, you'll see a warning.

If the user experience is better with you, I'll close the issue next week.

**Comment by mellery451** [comment]
This sounds reasonable to me. I have not had a chance to test this, but I'm fine with closing it as resolved. Thanks.
